      SUBROUTINE PARSLV(STF,RHV,X,NEQSOL,NCGSPC,IDSK,IDCG,PT,IPARM
     &                 ,ISLV,ITER,ITO)
C
      IMPLICIT REAL*8(A-H,O-Z)
      INTEGER*8 PT(64)
      DIMENSION STF(NCGSPC),RHV(NEQSOL),X(NEQSOL),IDSK(NEQSOL+1)
     &         ,IDCG(NCGSPC),IPARM(64)
C
      IF( ISLV == 3 ) THEN
        MTYPE = -2
      ELSE
        MTYPE = 11
      ENDIF
C
!      CALL PARDISO(PT,1,1,MTYPE,23,NEQSOL,STF,IDSK,IDCG,IDUM,1,IPARM,0
!     &            ,RHV,X,IERR)
C
      IF( IERR == -4 ) THEN
        IF( ITER > 1 ) THEN
          WRITE(ITO,'(A)') 'NONLINEAR CALCULATION DISPERSE.'
          CALL ERRSTP(90,ITO)
        ELSE
          WRITE(ITO,'(A)') 'CONSTRAINT CONDITION MIGHT BE WRONG.'
          CALL ERRSTP(23,ITO)
        ENDIF
      ENDIF
C
!      CALL PARDISO(PT,1,1,MTYPE,0,NEQSOL,STF,IDSK,IDCG,IDUM,1,IPARM,0
!     &            ,RHV,X,IERR)
C
      END
